/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Legion
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtQuestion2 = new swing.TextField();
        btnBack = new swing.Button();
        btnSubmit = new swing.Button();
        lblSecurityQuestions = new javax.swing.JLabel();
        lblQuestion2 = new javax.swing.JLabel();
        lblQuestion1 = new javax.swing.JLabel();
        txtQuestion1 = new swing.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txtQuestion2);
        txtQuestion2.setBounds(30, 200, 300, 41);

        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back.png"))); // NOI18N
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setRound(90);
        getContentPane().add(btnBack);
        btnBack.setBounds(70, 270, 30, 30);

        btnSubmit.setBackground(new java.awt.Color(4, 14, 143));
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(btnSubmit);
        btnSubmit.setBounds(120, 260, 120, 50);

        lblSecurityQuestions.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblSecurityQuestions.setForeground(new java.awt.Color(255, 255, 255));
        lblSecurityQuestions.setText("Security Questions");
        getContentPane().add(lblSecurityQuestions);
        lblSecurityQuestions.setBounds(30, 10, 320, 50);

        lblQuestion2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblQuestion2.setForeground(new java.awt.Color(255, 255, 255));
        lblQuestion2.setText("2. What is your favorite number?");
        getContentPane().add(lblQuestion2);
        lblQuestion2.setBounds(20, 170, 250, 22);

        lblQuestion1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblQuestion1.setForeground(new java.awt.Color(255, 255, 255));
        lblQuestion1.setText("1. What is your date of birth?");
        getContentPane().add(lblQuestion1);
        lblQuestion1.setBounds(20, 90, 220, 22);
        getContentPane().add(txtQuestion1);
        txtQuestion1.setBounds(30, 120, 300, 41);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btnBack;
    private swing.Button btnSubmit;
    private javax.swing.JLabel lblQuestion1;
    private javax.swing.JLabel lblQuestion2;
    private javax.swing.JLabel lblSecurityQuestions;
    private swing.TextField txtQuestion1;
    private swing.TextField txtQuestion2;
    // End of variables declaration//GEN-END:variables
}
