/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Design;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import swing.RippleEffectLabel;
import swing.RoundedBorder;
import util.ImageUtils;

/**
 *
 * @author Legion
 */
public class user_signup extends javax.swing.JFrame {

    /**
     * Creates new form user_signup
     */
    public user_signup() {
        initComponents();
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradiente1 = new swing.PanelGradiente();
        panelBorder1 = new swing.PanelBorder();
        slidehover = new swing.PanelSlide();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        slide = new swing.PanelSlide();
        lblsignup = new javax.swing.JLabel();
        btnSignIn = new swing.Button();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnDashBoard = new swing.Button();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        emailField1 = new swing.EmailField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        textField2 = new swing.TextField();
        textField5 = new swing.TextField();
        textField3 = new swing.TextField();
        textField6 = new swing.TextField();
        textField7 = new swing.TextField();
        passwordField1 = new swing.PasswordField();
        passwordField2 = new swing.PasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGradiente1.setColorPrimario(new java.awt.Color(153, 153, 255));
        panelGradiente1.setColorSecundario(new java.awt.Color(204, 204, 255));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        slidehover.setBackground(new java.awt.Color(255, 255, 255));
        slidehover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                slidehoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                slidehoverMouseExited(evt);
            }
        });
        slidehover.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Already have an account?");
        slidehover.add(jLabel1);
        jLabel1.setBounds(10, 120, 480, 90);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Create your account for free to access our services");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        slidehover.add(jLabel2);
        jLabel2.setBounds(20, 210, 430, 70);

        jLabel4 = new RippleEffectLabel("Sign In");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // You can adjust the font as needed
        jLabel4.setForeground(new java.awt.Color(255, 255, 255)); // Text color
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setBorder(new RoundedBorder(40, Color.WHITE, 2)); // Rounded border as in your original code
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        slidehover.add(jLabel4);
        jLabel4.setBounds(117, 356, 170, 60);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }

        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_signup.png"))); // NOI18N
        slidehover.add(jLabel3);
        jLabel3.setBounds(0, 0, 450, 620);

        panelBorder1.add(slidehover);
        slidehover.setBounds(10, 10, 450, 610);

        slide.setBackground(new java.awt.Color(255, 255, 255));
        slide.setLayout(null);

        lblsignup.setBackground(new java.awt.Color(255, 255, 255));
        lblsignup.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblsignup.setForeground(new java.awt.Color(54, 66, 81));
        lblsignup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsignup.setText("User SignUp");
        slide.add(lblsignup);
        lblsignup.setBounds(110, 40, 250, 48);

        btnSignIn.setBackground(new java.awt.Color(35, 39, 153));
        btnSignIn.setForeground(new java.awt.Color(255, 255, 255));
        btnSignIn.setText("Sign In");
        btnSignIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        slide.add(btnSignIn);
        btnSignIn.setBounds(180, 530, 129, 60);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Password :");
        slide.add(jLabel5);
        jLabel5.setBounds(50, 340, 90, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("First Name :");
        slide.add(jLabel6);
        jLabel6.setBounds(50, 100, 94, 25);

        btnDashBoard.setBackground(new java.awt.Color(123, 26, 7));
        btnDashBoard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashBoard.setText("DashBoard");
        btnDashBoard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDashBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashBoardActionPerformed(evt);
            }
        });
        slide.add(btnDashBoard);
        btnDashBoard.setBounds(420, 10, 110, 50);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Last Name :");
        slide.add(jLabel7);
        jLabel7.setBounds(290, 100, 94, 25);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Email :");
        slide.add(jLabel8);
        jLabel8.setBounds(50, 180, 94, 25);

        emailField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        slide.add(emailField1);
        emailField1.setBounds(40, 210, 400, 50);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Gender :");
        slide.add(jLabel9);
        jLabel9.setBounds(280, 260, 110, 25);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Contact No. :");
        slide.add(jLabel10);
        jLabel10.setBounds(50, 260, 110, 25);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        slide.add(jComboBox1);
        jComboBox1.setBounds(280, 290, 150, 50);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Confirm Password :");
        slide.add(jLabel13);
        jLabel13.setBounds(50, 430, 160, 25);

        textField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textField2.setPlaceholder("Enter Your Last Name");
        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        slide.add(textField2);
        textField2.setBounds(280, 130, 160, 50);

        textField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textField5.setPlaceholder("+977 98XXXXXXXX");
        textField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField5ActionPerformed(evt);
            }
        });
        slide.add(textField5);
        textField5.setBounds(40, 290, 180, 50);

        textField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textField3.setPlaceholder("Enter Your Last Name");
        textField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField3ActionPerformed(evt);
            }
        });
        slide.add(textField3);
        textField3.setBounds(280, 130, 160, 50);

        textField6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textField6.setPlaceholder("Enter Your First Name");
        textField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField6ActionPerformed(evt);
            }
        });
        slide.add(textField6);
        textField6.setBounds(40, 130, 160, 50);

        textField7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textField7.setPlaceholder("Enter Your First Name");
        textField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField7ActionPerformed(evt);
            }
        });
        slide.add(textField7);
        textField7.setBounds(40, 130, 160, 50);

        passwordField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordField1.setPlaceholder("Enter Your Password");
        passwordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordField1ActionPerformed(evt);
            }
        });
        slide.add(passwordField1);
        passwordField1.setBounds(40, 370, 390, 50);

        passwordField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordField2.setPlaceholder("Re-Enter Your Password");
        passwordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordField2ActionPerformed(evt);
            }
        });
        slide.add(passwordField2);
        passwordField2.setBounds(40, 460, 390, 50);

        panelBorder1.add(slide);
        slide.setBounds(460, 10, 530, 610);

        panelGradiente1.setLayer(panelBorder1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelGradiente1Layout = new javax.swing.GroupLayout(panelGradiente1);
        panelGradiente1.setLayout(panelGradiente1Layout);
        panelGradiente1Layout.setHorizontalGroup(
            panelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradiente1Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        panelGradiente1Layout.setVerticalGroup(
            panelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradiente1Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slidehoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slidehoverMouseEntered
    // Apply the blur effect to the image
    if (originalImage == null) {
        originalIcon = (ImageIcon) jLabel3.getIcon();
        originalImage = new BufferedImage(
                originalIcon.getIconWidth(),
                originalIcon.getIconHeight(),
                BufferedImage.TYPE_INT_ARGB);
        Graphics g = originalImage.getGraphics();
        originalIcon.paintIcon(null, g, 0, 0);
        g.dispose();
    }
    
    BufferedImage blurredAndScaledImage = ImageUtils.blurAndScaleImage(originalImage, 7, 1.01); 
    blurredIcon = new ImageIcon(blurredAndScaledImage);
    jLabel3.setIcon(blurredIcon);
    
    // Make sure the components are always visible
    if (!jLabel1.isVisible()) {
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel4.setVisible(true);
    }
    }//GEN-LAST:event_slidehoverMouseEntered

    private void slidehoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slidehoverMouseExited
  isMouseInside = false;
// Delay hiding after mouse exit, 
    new javax.swing.Timer(200, e -> {
        if (!isMouseInside) {
             if (jLabel1.isVisible()) {
                jLabel1.setVisible(false);
                jLabel2.setVisible(false);
                jLabel4.setVisible(false);
             }
            // Just restore the original image
            if (originalIcon != null) {
                jLabel3.setIcon(originalIcon);
            }
        }
        ((javax.swing.Timer) e.getSource()).stop(); // Stop the timer after the action
    }).start();
    }//GEN-LAST:event_slidehoverMouseExited

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnDashBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashBoardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashBoardActionPerformed

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed

    private void textField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField5ActionPerformed

    private void textField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField3ActionPerformed

    private void textField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField6ActionPerformed

    private void textField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField7ActionPerformed

    private void passwordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordField1ActionPerformed

    private void passwordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordField2ActionPerformed
private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {    
    isMouseInside = true;
    
    // Apply the blur effect to the image
    if (originalImage == null) {
        originalIcon = (ImageIcon) jLabel3.getIcon();
        originalImage = new BufferedImage(
                originalIcon.getIconWidth(),
                originalIcon.getIconHeight(),
                BufferedImage.TYPE_INT_ARGB);
        Graphics g = originalImage.getGraphics();
        originalIcon.paintIcon(null, g, 0, 0);
        g.dispose();
    }
    
    BufferedImage blurredAndScaledImage = ImageUtils.blurAndScaleImage(originalImage, 7, 1.01); 
    blurredIcon = new ImageIcon(blurredAndScaledImage);
    jLabel3.setIcon(blurredIcon);
    
    // Make sure the components are always visible
    if (!jLabel1.isVisible()) {
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel4.setVisible(true);
    }
}
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {  
       
        this.dispose();
    }
    /**
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btnDashBoard;
    private swing.Button btnSignIn;
    private swing.EmailField emailField1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblsignup;
    private swing.PanelBorder panelBorder1;
    private swing.PanelGradiente panelGradiente1;
    private swing.PasswordField passwordField1;
    private swing.PasswordField passwordField2;
    private swing.PanelSlide slide;
    private swing.PanelSlide slidehover;
    private swing.TextField textField2;
    private swing.TextField textField3;
    private swing.TextField textField5;
    private swing.TextField textField6;
    private swing.TextField textField7;
    // End of variables declaration//GEN-END:variables
private boolean isMouseInside = false;
private BufferedImage originalImage;
private ImageIcon originalIcon;
private ImageIcon blurredIcon;
private javax.swing.JLabel jLabel4;
}
